"""empty message

Revision ID: 2478538feb5e
Revises: fd3ed5e20d1b
Create Date: 2024-09-06 16:53:19.374045

"""

# With columns in questions id and username

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2478538feb5e'
down_revision: Union[str, None] = 'fd3ed5e20d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('id', sa.BigInteger(), nullable=False))
    op.add_column('questions', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint('questions_name_key', 'questions', type_='unique')
    op.drop_constraint('questions_user_id_key', 'questions', type_='unique')
    op.create_unique_constraint(None, 'questions', ['username'])
    op.create_unique_constraint(None, 'questions', ['id'])
    op.drop_constraint('questions_name_fkey', 'questions', type_='foreignkey')
    op.drop_constraint('questions_user_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'users', ['username'], ['username'])
    op.create_foreign_key(None, 'questions', 'users', ['id'], ['id'])
    op.drop_column('questions', 'name')
    op.drop_column('questions', 'user_id')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('questions', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_user_id_fkey', 'questions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('questions_name_fkey', 'questions', 'users', ['name'], ['username'])
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'questions', type_='unique')
    op.create_unique_constraint('questions_user_id_key', 'questions', ['user_id'])
    op.create_unique_constraint('questions_name_key', 'questions', ['name'])
    op.drop_column('questions', 'username')
    op.drop_column('questions', 'id')
    # ### end Alembic commands ###
